#!/bin/sh
# this script compiles BotClassifyAll and starts it with one or more models
# the MODELS/ directory is a link to the latest set of models generated by botremodel.sh
# run botremodel.sh before running this script
# run test1000.sh to test the predictions against a model
# prepare to be disappointed :)

cd /srv/cal/src/apache/ml/analysis
cp=.:./java/postgresql.jar:./java/weka-pg.jar 
/usr/bin/javac -cp $cp BotClassifyAll.java

# some other options: 
# BFTree.model J48.model RandomForest.model REPTree.model NBTree.model RandomTree.model SimpleCart.model
# only uncomment one of these...
/usr/bin/java -cp $cp BotClassifyAll botstats MODELS/*.model | \
# /usr/bin/java -cp $cp BotClassifyAll botstats MODELS/SimpleCart.model | \
# /usr/bin/java -cp $cp BotClassifyAll botstats MODELS/BFTree.model | \
# /usr/bin/java -cp $cp BotClassifyAll botstats MODELS/J48.model | \
# /usr/bin/java -cp $cp BotClassifyAll botstats MODELS/J48*.model | \
# /usr/bin/java -cp $cp BotClassifyAll botstats MODELS/RandomForest.model | \
    perl -ne '($pred, $ip) = split " "; $pred = ($pred < 0? -1 : 2); print "$pred $ip\n"' > predictions.txt
./vwfill.sh CURRENTMODEL >> predictions.txt
# ./fill-memcache.py 127.0.0.1:11211 predictions.txt
./fill-memcache.py 206.12.16.237:11211 predictions.txt
