#!/bin/sh
# this script compiles BotClassifier and starts it with one or more models
# the MODELS/ directory is a link to the latest set of models generated by botremodel.sh
# run botremodel.sh before running this script
# run test1000.sh to test the predictions against a model
# prepare to be disappointed :)

cd /srv/cal/src/apache/ml/analysis
cp=.:./java/postgresql.jar:./java/weka-pg.jar 
/usr/bin/javac -cp $cp BotClassifier.java

# some other options: 
# BFTree.model J48.model RandomForest.model REPTree.model NBTree.model RandomTree.model SimpleCart.model
# /usr/bin/java -cp $cp BotClassifier 39999 botstats MODELS/*.model
# /usr/bin/java -cp $cp BotClassifier 39999 botstats MODELS/SimpleCart.model
# /usr/bin/java -cp $cp BotClassifier 39999 botstats MODELS/BFTree.model
/usr/bin/java -cp $cp BotClassifier 39999 botstats MODELS/J48.model
# /usr/bin/java -cp $cp BotClassifier 39999 botstats MODELS/J48*.model
# /usr/bin/java -cp $cp BotClassifier 39999 botstats MODELS/RandomForest.model
