#!/bin/sh
# this script compiles BotClassifier and starts it with one or more models
# the MODELS/ directory is a link to the latest set of models generated by botremodel.sh
# run botremodel.sh before running this script
# run test1000.sh to test the predictions against a model
# prepare to be disappointed :)

cd /srv/cal/src/apache/ml/analysis
export cp=.:./java/postgresql.jar:./java/weka-pg.jar 
/usr/bin/javac -cp $cp BotPrintClassifier.java

/usr/bin/java -cp $cp BotPrintClassifier $@
